website/auth.py
from flask import Blueprint, redirect, render_template, request,flash, session, url_for, abort 
from .input_validation import *
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user, UserMixin
from io import BytesIO
import pyqrcode

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET','POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        # check if the user exist already in DB
        user = User.query.filter_by(email=email).first()
        print(password)
        print(request.form.get('password'))

        # if  the user exists check if the password enterd and stored are same
        if user :
            email = request.form.get('email')
            password = request.form.get('password')
            token = request.form.get('token')
            user = User.query.filter_by(email=email).first()
            # check for password and OTP too
            print("email:",email)
            print("Token",token) 
            print("OTP check", user.verify_totp(token))
            if check_password_hash(user.password,password) and user.verify_totp(token):
                flash('Logged in Successfully!', category='success')
                
                # when the browser closes, if the user is logged in, it will remember
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password or OTP Token', category='error')
        # if the user doesnt exists
        else:
            flash('User not found in our Database', category='error')
            return redirect(url_for("auth.sign_up"))

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Bye,you have been logged out!",category="success")
    return redirect(url_for('auth.login'))



@auth.route('/sign-up',methods=['GET','POST'])
def sign_up():
    # we are diff GET and POST request
    if request.method == 'POST':
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        # check if we are grabbing the values from UI correctly
        #print(email,firstName,password1,password2)



        # Before creating a new account, check if the user(email) already exists in our DB
        user = User.query.filter_by(email=email).first()
        print("Sign-up 1st occ user", user)
        
        if user and user.is_active:
           flash('Email already exists in our Database',category='error')
        # basic checks, and flash for showing messages on UI
        # email length check
        elif len(email) < 4:
            flash ('Email must be greater than 4 characters', category='error')
        # firstname check
        # 1. length
        # 2. shouldnt start with numbers or special chrs
        elif len(firstName) < 3:
            flash('Fist Name must be greater than 3 characters',category='error')
        # password check
        # 1. min length = 8
        # 2. 1 uppercase 1 lowercase 1 specialchr
        elif len(password1) < 7:
            flash("Password must be at least 7 characters",category='error')
        elif not contains_chr(password1):
            flash("Password must contains at least 1 special characters",category='error')
        elif not contains_upper(password1):
            flash("Password must contain atleast 1 uppercase letter",category="error")
        elif not contains_lower(password1):
            flash("Password must contain atleast 1 lowercase alphabet",category="error")
        elif password1 != password2:
            flash("Password not maching",category='error')
        else:


            # creating a new user
            new_user = User(email=email, firstName=firstName, password=generate_password_hash(password1, method="sha256"))
                
            # adding this new user to staging area
            db.session.add(new_user)

            # adding this user to DB
            db.session.commit()
            user = User.query.filter_by(email=email).first()
            print("Sign-up 2nd occ user", user)
            login_user(user, remember=True)

            session['email'] = email
            print(session['email']) 
            return redirect(url_for('auth.qr'))

        
        flash(f"Account Created, Welcome {firstName}",category='success')
        return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

@auth.route('/qr', methods=['GET','POST'])
def qr():
    if 'email' not in session:
        return redirect(url_for('auth.sign_up'))
    email = session['email']
    print("/qr - email",email)
    user = User.query.filter_by(email=email).first()
    print("/qr - user",user)
    # if user is None:
    #     return redirect(url_for('auth.sign_up'))
    return render_template("qr.html", user=current_user)


# Generate QR code
@auth.route('/generate_qr', methods=['GET','POST'])
def generate_qr():
    if 'email' not in session:
        return redirect(url_for('auth.sign_up'))
    email = session['email']
    email = 'user100@email.com'
    user = User.query.filter_by(email=email).first()

    if user is None:
        abort(404)

    del session['email']

    print("current_user=",current_user)
    url = pyqrcode.create(current_user.get_totp_uri())
    stream = BytesIO()
    url.svg(stream, scale=5)
    return stream.getvalue(), 200, {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'
        }

website/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>

    <!-- Favicon -->

    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/favicon_io/apple-touch-icon.png')}}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicon_io/favicon-32x32.png')}}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicon_io/favicon-16x16.png')}}">

    
    <!-- CSS only bootstrap CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- Fontawesome CDN -->
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    <title>{% block title %}{% endblock %}</title>

</head>

<body>
    <!-- Navigation bar -->
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/home">fnote-mfa</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-link active" aria-current="page" href="/home">Home</a>
                        <a class="nav-link" href="/logout" id="logout">Logout</a>
                        
                        {% else %}
                        <a class="nav-link" href="/login" id="login">Login</a>
                        <a class=" nav-link " href="/sign-up" id="signUp">Sign Up</a>
                        {% endif %}

                    </div>
                </div>
            </div>
        </nav>
    </header>


    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                {% if category == 'error' %}
                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                     <div>   
                         {{ message }}  
                        <button type="button" class="btn-close float-right" aria-label="Close"data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                     </div>    
                    
                    </div>
                {% else %}
                    <div class="alert alert-success alter-dismissable fade show" role="alert">
                        <div> 
                             {{ message }}
                    <button type="button" class="btn-close float-right" aria-label="Close" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                    </div>

                {% endif %}
            {% endfor %}
        {% endif %}
    {% endwith %}


    <div class="container">
        {% block content %}
        {% endblock %}
    </div>


    <script type="text/javascript" src="{{url_for('static', filename='index.js')}}"></script>

    <!-- for styling -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet"
          href=
"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"> 
  <!-- CSS only bootstrap CDN -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
  integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    
 
<!--<script src=
"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js">-->
  <!--</script>
    <script src=
"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js">
    </script>
    <script src=
"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"> -->


</body>

</html>

website/templates/home.html
{% extends "base.html" %}

{% block title %} Note Taker {% endblock %}

{% block content %}

<h1 align="center"> {{ user.firstName }}'s Notes </h1>

<ul class="list-group list-group-flush" id="notes">
    {% for note in user.notes %}
        <li class="list-group-item">{{note.data}}
            <button type="button" class="btn-close float-right" onclick='deleteNote({{note.id}})''>
                <span aria-hidden="true">&times;</span>
            </button>
        </li>
    {% endfor %}
</ul>

<form method="POST">
    <textarea name="note" id="note" class="form-control"></textarea>
    <div align="center" >
        <br>
        <button type="submit" class="btn btn-primary">Add Note</button>
    </div>
</form>
{% endblock %}

website/templates/login.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block content %}
<!-- Signup Form -->
<form method="post">
    <h3 align="center"> Login </h3>

    <!-- For email address -->
    <div class="form-group">
        <label for="email">
            Email Address
        </label>
        <!-- "name=" is what we get the value from user and pass to backend-->
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <br>
    <!-- for password -->
    <div class="form-group">
        <label for="password1">
            Password
        </label>
        <!-- "name=" is what we get the value from user and pass to backend-->
        <input type="password" class="form-control" id="password1" name="password" placeholder="Password">
    </div>

    <div class="form-group">
        <label for="email">
            OTP Code (6 digit code from Authenticator App)
        </label>
        <!-- "name=" is what we get the value from user and pass to backend-->
        <input type="number" class="form-control" id="token" name="token" placeholder="XXXXXX">
    </div>

<br>


<form method="POST"> <!-- Sends POST request to flask server -->
    <!-- {{ recaptcha }} Refer to 'recaptcha' variable in main.py -->
    <button type="submit" class="btn btn-primary"> Login </button>
</form>

<!-- <script src="https://www.google.com/recaptcha/enterprise.js?render=6Ld4ED0lAAAAAG71-spXDfk2N6HmybuG8RxxXPFh"></script>
<form action="?" method="POST">
              <div class="g-recaptcha" data-sitekey="6Ld4ED0lAAAAAG71-spXDfk2N6HmybuG8RxxXPFh" data-action="LOGIN"></div>
              <br/>
              <input type="submit" value="Submit">
            </form> -->

<!-- For reCapcha--> 
<!-- <script src="https://www.google.com/recaptcha/enterprise.js?render=6Ld4ED0lAAAAAG71-spXDfk2N6HmybuG8RxxXPFh"></script>
<script>
grecaptcha.enterprise.ready(function() {
    grecaptcha.enterprise.execute('6Ld4ED0lAAAAAG71-spXDfk2N6HmybuG8RxxXPFh', {action: 'login'}).then(function(token) {

    });
});
</script> -->
<br>
<a href="/sign-up" id="signUp">New User? Signup here</a>
</form>


{% endblock %}

website/templates/qr.html
{% extends "base.html" %}

{% block title %} Login {% endblock %}

{% block content %}

<!-- <div class="row">
    <div class="col-md-4"> -->
        <div align="center">
        <h1> 2nd Factor Authentication</h1> 
        <h1>Scan the QR Code Below</h1>
        <p>
            <img id="generate-qr" src="{{ url_for('auth.generate_qr') }}" alt="QR Code" />
        </p>
        
        <p>
            <a class="btn btn-dark" style="width: 268px;" href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2" target="_blank">
                <img src="{{ url_for('static', filename='images/Google_Authenticator_logo.svg')}}" alt="Google Authenticator" style="width: 20px; height: 20px;">
                Install Google Authenticator
            </a>
        </p>

        <p>
            <a class="btn btn-dark" href="https://play.google.com/store/apps/details?id=com.azure.authenticator" target="_blank">
                <img src="{{ url_for('static', filename='images/microsoft-authenticator-logo.svg')}}" alt="Microsoft Authenticator" style="width: 20px; height: 20px;">
                Install Microsoft Authenticator
            </a>
        </p>
        <p>
            Once scanned, you can <a href="{{ url_for('auth.login') }}">Login</a>
        </p>
    </div>
    </div>
</div>


{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}

{% block title %} Sign Up {% endblock %}

{% block content %}
<!-- Signup Form -->
<form method="post">
    <h3 align="center"> Sign Up </h3>

    <!-- For email address -->
    <div class="form-group">
        <label for="email">
            Email Address
        </label>
        <!-- "name=" is what we get the value from user and pass to backend-->
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
    </div>
    <br>
    <!-- For first name -->
    <div class="form-group">
        <label for="firstName">
            First Name
        </label>
        <!-- "name=" is what we get the value from user and pass to backend-->
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="First Name">
        <ul>
            <li class="text-muted">First Name must be atleast 4 characters long.</li>
            <li class="text-muted">First Name CANNOT start with a number or special characters.</li>
        </ul>
    </div>
    <!-- for password -->
    <div class="form-group">
        <label for="password1">
            Password
        </label>
        <!-- "name=" is what we get the value from user and pass to backend-->
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Password">
        <ul>
            <li class="text-muted">Password must be atleast 8 characters long.</li>
            <li class="text-muted">Password must contain atleast 1 UpperCase alphabet.</li>
            <li class="text-muted">Password must contain atleast 1 lowerCase alphabet.</li>
            <li class="text-muted">Password must contain atleast 1 special characters(eg:#,@,$,%,&,*etc).</li>
        </ul>
    </div>
    <!-- confirm password -->
    <div class="form-group">
        <label for="password2">
            Confirm Password
        </label>
        <!-- "name=" is what we get the value from user and pass to backend-->
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password">
    </div>
<br>
<!-- submit button-->
<button type="submit" class="btn btn-primary"> Submit </button>

<br>
<a href="/login" id="login">Already have an account? Login here</a>

</form>


{% endblock %}